// Creates the deck for the game.
// Adds card objects, images, and pushes into a stack

package javaFiles;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.*;

import javafx.scene.image.Image;

public class DeckV3 extends Stack<Card> {
	
	public DeckV3() throws FileNotFoundException {
		
		Card	bP1	=	new	Card("Blue",	1,	"Parallelogram",	"Solid",	"C://Users//deane//GitHub//Coleccion//Parallelograms//Colección_Blue_Parallelogram_1.png"); 
		Card	bP2	=	new	Card("Blue",	2,	"Parallelogram",	"Solid",	"C://Users//deane//GitHub//Coleccion//Parallelograms//Colección_Blue_Parallelogram_2.png");
		Card	bP3	=	new	Card("Blue",	3,	"Parallelogram",	"Solid",	"C://Users//deane//GitHub//Coleccion//Parallelograms//Colección_Blue_Parallelogram_3.png");
		Card	bPE1	=	new	Card("Blue",	1,	"Parallelogram",	"Empty",	"C://Users//deane//GitHub//Coleccion//Parallelograms//Colección_Blue_Parallelogram_E_1.png"); 
		Card	bPE2	=	new	Card("Blue",	2,	"Parallelogram",	"Empty",	"C://Users//deane//GitHub//Coleccion//Parallelograms//Colección_Blue_Parallelogram_E_2.png");
		Card	bPE3	=	new	Card("Blue",	3,	"Parallelogram",	"Empty",	"C://Users//deane//GitHub//Coleccion//Parallelograms//Colección_Blue_Parallelogram_E_3.png");
		Card	bPS1	=	new	Card("Blue",	1,	"Parallelogram",	"Grid",	"C://Users//deane//GitHub//Coleccion//Parallelograms//Colección_Blue_Parallelogram_S_1.png"); 
		Card	bPS2	=	new	Card("Blue",	2,	"Parallelogram",	"Grid",	"C://Users//deane//GitHub//Coleccion//Parallelograms//Colección_Blue_Parallelogram_S_2.png");
		Card	bPS3	=	new	Card("Blue",	3,	"Parallelogram",	"Grid",	"C://Users//deane//GitHub//Coleccion//Parallelograms//Colección_Blue_Parallelogram_S_3.png");
		Card	gP1	=	new	Card("Green",	1,	"Parallelogram",	"Solid",	"C://Users//deane//GitHub//Coleccion//Parallelograms//Colección_Green_Parallelogram_1.png"); 
		Card	gP2	=	new	Card("Green",	2,	"Parallelogram",	"Solid",	"C://Users//deane//GitHub//Coleccion//Parallelograms//Colección_Green_Parallelogram_2.png");
		Card	gP3	=	new	Card("Green",	3,	"Parallelogram",	"Solid",	"C://Users//deane//GitHub//Coleccion//Parallelograms//Colección_Green_Parallelogram_3.png");
		Card	gPE1	=	new	Card("Green",	1,	"Parallelogram",	"Empty",	"C://Users//deane//GitHub//Coleccion//Parallelograms//Colección_Green_Parallelogram_E_1.png"); 
		Card	gPE2	=	new	Card("Green",	2,	"Parallelogram",	"Empty",	"C://Users//deane//GitHub//Coleccion//Parallelograms//Colección_Green_Parallelogram_E_2.png");
		Card	gPE3	=	new	Card("Green",	3,	"Parallelogram",	"Empty",	"C://Users//deane//GitHub//Coleccion//Parallelograms//Colección_Green_Parallelogram_E_3.png");
		Card	gPS1	=	new	Card("Green",	1,	"Parallelogram",	"Grid",	"C://Users//deane//GitHub//Coleccion//Parallelograms//Colección_Green_Parallelogram_S_1.png"); 
		Card	gPS2	=	new	Card("Green",	2,	"Parallelogram",	"Grid",	"C://Users//deane//GitHub//Coleccion//Parallelograms//Colección_Green_Parallelogram_S_2.png");
		Card	gPS3	=	new	Card("Green",	3,	"Parallelogram",	"Grid",	"C://Users//deane//GitHub//Coleccion//Parallelograms//Colección_Green_Parallelogram_S_3.png");
		Card	oP1	=	new	Card("Orange",	1,	"Parallelogram",	"Solid",	"C://Users//deane//GitHub//Coleccion//Parallelograms//Colección_Orange_Parallelogram_1.png"); 
		Card	oP2	=	new	Card("Orange",	2,	"Parallelogram",	"Solid",	"C://Users//deane//GitHub//Coleccion//Parallelograms//Colección_Orange_Parallelogram_2.png");
		Card	oP3	=	new	Card("Orange",	3,	"Parallelogram",	"Solid",	"C://Users//deane//GitHub//Coleccion//Parallelograms//Colección_Orange_Parallelogram_3.png");
		Card	oPE1	=	new	Card("Orange",	1,	"Parallelogram",	"Empty",	"C://Users//deane//GitHub//Coleccion//Parallelograms//Colección_Orange_Parallelogram_E_1.png"); 
		Card	oPE2	=	new	Card("Orange",	2,	"Parallelogram",	"Empty",	"C://Users//deane//GitHub//Coleccion//Parallelograms//Colección_Orange_Parallelogram_E_2.png");
		Card	oPE3	=	new	Card("Orange",	3,	"Parallelogram",	"Empty",	"C://Users//deane//GitHub//Coleccion//Parallelograms//Colección_Orange_Parallelogram_E_3.png");
		Card	oPS1	=	new	Card("Orange",	1,	"Parallelogram",	"Grid",	"C://Users//deane//GitHub//Coleccion//Parallelograms//Colección_Orange_Parallelogram_S_1.png"); 
		Card	oPS2	=	new	Card("Orange",	2,	"Parallelogram",	"Grid",	"C://Users//deane//GitHub//Coleccion//Parallelograms//Colección_Orange_Parallelogram_S_2.png");
		Card	oPS3	=	new	Card("Orange",	3,	"Parallelogram",	"Grid",	"C://Users//deane//GitHub//Coleccion//Parallelograms//Colección_Orange_Parallelogram_S_3.png");
		Card	rP1	=	new	Card("Red",	1,	"Parallelogram",	"Solid",	"C://Users//deane//GitHub//Coleccion//Parallelograms//Colección_Red_Parallelogram_1.png"); 
		Card	rP2	=	new	Card("Red",	2,	"Parallelogram",	"Solid",	"C://Users//deane//GitHub//Coleccion//Parallelograms//Colección_Red_Parallelogram_2.png");
		Card	rP3	=	new	Card("Red",	3,	"Parallelogram",	"Solid",	"C://Users//deane//GitHub//Coleccion//Parallelograms//Colección_Red_Parallelogram_3.png");
		Card	rPE1	=	new	Card("Red",	1,	"Parallelogram",	"Empty",	"C://Users//deane//GitHub//Coleccion//Parallelograms//Colección_Red_Parallelogram_E_1.png"); 
		Card	rPE2	=	new	Card("Red",	2,	"Parallelogram",	"Empty",	"C://Users//deane//GitHub//Coleccion//Parallelograms//Colección_Red_Parallelogram_E_2.png");
		Card	rPE3	=	new	Card("Red",	3,	"Parallelogram",	"Empty",	"C://Users//deane//GitHub//Coleccion//Parallelograms//Colección_Red_Parallelogram_E_3.png");
		Card	rPS1	=	new	Card("Red",	1,	"Parallelogram",	"Grid",	"C://Users//deane//GitHub//Coleccion//Parallelograms//Colección_Red_Parallelogram_S_1.png"); 
		Card	rPS2	=	new	Card("Red",	2,	"Parallelogram",	"Grid",	"C://Users//deane//GitHub//Coleccion//Parallelograms//Colección_Red_Parallelogram_S_2.png");
		Card	rPS3	=	new	Card("Red",	3,	"Parallelogram",	"Grid",	"C://Users//deane//GitHub//Coleccion//Parallelograms//Colección_Red_Parallelogram_S_3.png");
		Card	bR1	=	new	Card("Blue",	1,	"Rectangle",	"Solid",	"C://Users//deane//GitHub//Coleccion//Rectangles//Colección_Blue_Rectangle_1.png"); 
		Card	bR2	=	new	Card("Blue",	2,	"Rectangle",	"Solid",	"C://Users//deane//GitHub//Coleccion//Rectangles//Colección_Blue_Rectangle_2.png");
		Card	bR3	=	new	Card("Blue",	3,	"Rectangle",	"Solid",	"C://Users//deane//GitHub//Coleccion//Rectangles//Colección_Blue_Rectangle_3.png");
		Card	bRE1	=	new	Card("Blue",	1,	"Rectangle",	"Empty",	"C://Users//deane//GitHub//Coleccion//Rectangles//Colección_Blue_Rectangle_E_1.png"); 
		Card	bRE2	=	new	Card("Blue",	2,	"Rectangle",	"Empty",	"C://Users//deane//GitHub//Coleccion//Rectangles//Colección_Blue_Rectangle_E_2.png");
		Card	bRE3	=	new	Card("Blue",	3,	"Rectangle",	"Empty",	"C://Users//deane//GitHub//Coleccion//Rectangles//Colección_Blue_Rectangle_E_3.png");
		Card	bRS1	=	new	Card("Blue",	1,	"Rectangle",	"Grid",	"C://Users//deane//GitHub//Coleccion//Rectangles//Colección_Blue_Rectangle_S_1.png"); 
		Card	bRS2	=	new	Card("Blue",	2,	"Rectangle",	"Grid",	"C://Users//deane//GitHub//Coleccion//Rectangles//Colección_Blue_Rectangle_S_2.png");
		Card	bRS3	=	new	Card("Blue",	3,	"Rectangle",	"Grid",	"C://Users//deane//GitHub//Coleccion//Rectangles//Colección_Blue_Rectangle_S_3.png");
		Card	gR1	=	new	Card("Green",	1,	"Rectangle",	"Solid",	"C://Users//deane//GitHub//Coleccion//Rectangles//Colección_Green_Rectangle_1.png"); 
		Card	gR2	=	new	Card("Green",	2,	"Rectangle",	"Solid",	"C://Users//deane//GitHub//Coleccion//Rectangles//Colección_Green_Rectangle_2.png");
		Card	gR3	=	new	Card("Green",	3,	"Rectangle",	"Solid",	"C://Users//deane//GitHub//Coleccion//Rectangles//Colección_Green_Rectangle_3.png");
		Card	gRE1	=	new	Card("Green",	1,	"Rectangle",	"Empty",	"C://Users//deane//GitHub//Coleccion//Rectangles//Colección_Green_Rectangle_E_1.png"); 
		Card	gRE2	=	new	Card("Green",	2,	"Rectangle",	"Empty",	"C://Users//deane//GitHub//Coleccion//Rectangles//Colección_Green_Rectangle_E_2.png");
		Card	gRE3	=	new	Card("Green",	3,	"Rectangle",	"Empty",	"C://Users//deane//GitHub//Coleccion//Rectangles//Colección_Green_Rectangle_E_3.png");
		Card	gRS1	=	new	Card("Green",	1,	"Rectangle",	"Grid",	"C://Users//deane//GitHub//Coleccion//Rectangles//Colección_Green_Rectangle_S_1.png"); 
		Card	gRS2	=	new	Card("Green",	2,	"Rectangle",	"Grid",	"C://Users//deane//GitHub//Coleccion//Rectangles//Colección_Green_Rectangle_S_2.png");
		Card	gRS3	=	new	Card("Green",	3,	"Rectangle",	"Grid",	"C://Users//deane//GitHub//Coleccion//Rectangles//Colección_Green_Rectangle_S_3.png");
		Card	oR1	=	new	Card("Orange",	1,	"Rectangle",	"Solid",	"C://Users//deane//GitHub//Coleccion//Rectangles//Colección_Orange_Rectangle_1.png"); 
		Card	oR2	=	new	Card("Orange",	2,	"Rectangle",	"Solid",	"C://Users//deane//GitHub//Coleccion//Rectangles//Colección_Orange_Rectangle_2.png");
		Card	oR3	=	new	Card("Orange",	3,	"Rectangle",	"Solid",	"C://Users//deane//GitHub//Coleccion//Rectangles//Colección_Orange_Rectangle_3.png");
		Card	oRE1	=	new	Card("Orange",	1,	"Rectangle",	"Empty",	"C://Users//deane//GitHub//Coleccion//Rectangles//Colección_Orange_Rectangle_E_1.png"); 
		Card	oRE2	=	new	Card("Orange",	2,	"Rectangle",	"Empty",	"C://Users//deane//GitHub//Coleccion//Rectangles//Colección_Orange_Rectangle_E_2.png");
		Card	oRE3	=	new	Card("Orange",	3,	"Rectangle",	"Empty",	"C://Users//deane//GitHub//Coleccion//Rectangles//Colección_Orange_Rectangle_E_3.png");
		Card	oRS1	=	new	Card("Orange",	1,	"Rectangle",	"Grid",	"C://Users//deane//GitHub//Coleccion//Rectangles//Colección_Orange_Rectangle_S_1.png"); 
		Card	oRS2	=	new	Card("Orange",	2,	"Rectangle",	"Grid",	"C://Users//deane//GitHub//Coleccion//Rectangles//Colección_Orange_Rectangle_S_2.png");
		Card	oRS3	=	new	Card("Orange",	3,	"Rectangle",	"Grid",	"C://Users//deane//GitHub//Coleccion//Rectangles//Colección_Orange_Rectangle_S_3.png");
		Card	rR1	=	new	Card("Red",	1,	"Rectangle",	"Solid",	"C://Users//deane//GitHub//Coleccion//Rectangles//Colección_Red_Rectangle_1.png"); 
		Card	rR2	=	new	Card("Red",	2,	"Rectangle",	"Solid",	"C://Users//deane//GitHub//Coleccion//Rectangles//Colección_Red_Rectangle_2.png");
		Card	rR3	=	new	Card("Red",	3,	"Rectangle",	"Solid",	"C://Users//deane//GitHub//Coleccion//Rectangles//Colección_Red_Rectangle_3.png");
		Card	rRE1	=	new	Card("Red",	1,	"Rectangle",	"Empty",	"C://Users//deane//GitHub//Coleccion//Rectangles//Colección_Red_Rectangle_E_1.png"); 
		Card	rRE2	=	new	Card("Red",	2,	"Rectangle",	"Empty",	"C://Users//deane//GitHub//Coleccion//Rectangles//Colección_Red_Rectangle_E_2.png");
		Card	rRE3	=	new	Card("Red",	3,	"Rectangle",	"Empty",	"C://Users//deane//GitHub//Coleccion//Rectangles//Colección_Red_Rectangle_E_3.png");
		Card	rRS1	=	new	Card("Red",	1,	"Rectangle",	"Grid",	"C://Users//deane//GitHub//Coleccion//Rectangles//Colección_Red_Rectangle_S_1.png"); 
		Card	rRS2	=	new	Card("Red",	2,	"Rectangle",	"Grid",	"C://Users//deane//GitHub//Coleccion//Rectangles//Colección_Red_Rectangle_S_2.png");
		Card	rRS3	=	new	Card("Red",	3,	"Rectangle",	"Grid",	"C://Users//deane//GitHub//Coleccion//Rectangles//Colección_Red_Rectangle_S_3.png");
		Card	bS1	=	new	Card("Blue",	1,	"Semicircle",	"Solid",	"C://Users//deane//GitHub//Coleccion//Semicircles//Colección_Blue_Semicircle_1.png"); 
		Card	bS2	=	new	Card("Blue",	2,	"Semicircle",	"Solid",	"C://Users//deane//GitHub//Coleccion//Semicircles//Colección_Blue_Semicircle_2.png");
		Card	bS3	=	new	Card("Blue",	3,	"Semicircle",	"Solid",	"C://Users//deane//GitHub//Coleccion//Semicircles//Colección_Blue_Semicircle_3.png");
		Card	bSE1	=	new	Card("Blue",	1,	"Semicircle",	"Empty",	"C://Users//deane//GitHub//Coleccion//Semicircles//Colección_Blue_Semicircle_E_1.png"); 
		Card	bSE2	=	new	Card("Blue",	2,	"Semicircle",	"Empty",	"C://Users//deane//GitHub//Coleccion//Semicircles//Colección_Blue_Semicircle_E_2.png");
		Card	bSE3	=	new	Card("Blue",	3,	"Semicircle",	"Empty",	"C://Users//deane//GitHub//Coleccion//Semicircles//Colección_Blue_Semicircle_E_3.png");
		Card	bSS1	=	new	Card("Blue",	1,	"Semicircle",	"Grid",	"C://Users//deane//GitHub//Coleccion//Semicircles//Colección_Blue_Semicircle_S_1.png"); 
		Card	bSS2	=	new	Card("Blue",	2,	"Semicircle",	"Grid",	"C://Users//deane//GitHub//Coleccion//Semicircles//Colección_Blue_Semicircle_S_2.png");
		Card	bSS3	=	new	Card("Blue",	3,	"Semicircle",	"Grid",	"C://Users//deane//GitHub//Coleccion//Semicircles//Colección_Blue_Semicircle_S_3.png");
		Card	gS1	=	new	Card("Green",	1,	"Semicircle",	"Solid",	"C://Users//deane//GitHub//Coleccion//Semicircles//Colección_Green_Semicircle_1.png"); 
		Card	gS2	=	new	Card("Green",	2,	"Semicircle",	"Solid",	"C://Users//deane//GitHub//Coleccion//Semicircles//Colección_Green_Semicircle_2.png");
		Card	gS3	=	new	Card("Green",	3,	"Semicircle",	"Solid",	"C://Users//deane//GitHub//Coleccion//Semicircles//Colección_Green_Semicircle_3.png");
		Card	gSE1	=	new	Card("Green",	1,	"Semicircle",	"Empty",	"C://Users//deane//GitHub//Coleccion//Semicircles//Colección_Green_Semicircle_E_1.png"); 
		Card	gSE2	=	new	Card("Green",	2,	"Semicircle",	"Empty",	"C://Users//deane//GitHub//Coleccion//Semicircles//Colección_Green_Semicircle_E_2.png");
		Card	gSE3	=	new	Card("Green",	3,	"Semicircle",	"Empty",	"C://Users//deane//GitHub//Coleccion//Semicircles//Colección_Green_Semicircle_E_3.png");
		Card	gSS1	=	new	Card("Green",	1,	"Semicircle",	"Grid",	"C://Users//deane//GitHub//Coleccion//Semicircles//Colección_Green_Semicircle_S_1.png"); 
		Card	gSS2	=	new	Card("Green",	2,	"Semicircle",	"Grid",	"C://Users//deane//GitHub//Coleccion//Semicircles//Colección_Green_Semicircle_S_2.png");
		Card	gSS3	=	new	Card("Green",	3,	"Semicircle",	"Grid",	"C://Users//deane//GitHub//Coleccion//Semicircles//Colección_Green_Semicircle_S_3.png");
		Card	oS1	=	new	Card("Orange",	1,	"Semicircle",	"Solid",	"C://Users//deane//GitHub//Coleccion//Semicircles//Colección_Orange_Semicircle_1.png"); 
		Card	oS2	=	new	Card("Orange",	2,	"Semicircle",	"Solid",	"C://Users//deane//GitHub//Coleccion//Semicircles//Colección_Orange_Semicircle_2.png");
		Card	oS3	=	new	Card("Orange",	3,	"Semicircle",	"Solid",	"C://Users//deane//GitHub//Coleccion//Semicircles//Colección_Orange_Semicircle_3.png");
		Card	oSE1	=	new	Card("Orange",	1,	"Semicircle",	"Empty",	"C://Users//deane//GitHub//Coleccion//Semicircles//Colección_Orange_Semicircle_E_1.png"); 
		Card	oSE2	=	new	Card("Orange",	2,	"Semicircle",	"Empty",	"C://Users//deane//GitHub//Coleccion//Semicircles//Colección_Orange_Semicircle_E_2.png");
		Card	oSE3	=	new	Card("Orange",	3,	"Semicircle",	"Empty",	"C://Users//deane//GitHub//Coleccion//Semicircles//Colección_Orange_Semicircle_E_3.png");
		Card	oSS1	=	new	Card("Orange",	1,	"Semicircle",	"Grid",	"C://Users//deane//GitHub//Coleccion//Semicircles//Colección_Orange_Semicircle_S_1.png"); 
		Card	oSS2	=	new	Card("Orange",	2,	"Semicircle",	"Grid",	"C://Users//deane//GitHub//Coleccion//Semicircles//Colección_Orange_Semicircle_S_2.png");
		Card	oSS3	=	new	Card("Orange",	3,	"Semicircle",	"Grid",	"C://Users//deane//GitHub//Coleccion//Semicircles//Colección_Orange_Semicircle_S_3.png");
		Card	rS1	=	new	Card("Red",	1,	"Semicircle",	"Solid",	"C://Users//deane//GitHub//Coleccion//Semicircles//Colección_Red_Semicircle_1.png"); 
		Card	rS2	=	new	Card("Red",	2,	"Semicircle",	"Solid",	"C://Users//deane//GitHub//Coleccion//Semicircles//Colección_Red_Semicircle_2.png");
		Card	rS3	=	new	Card("Red",	3,	"Semicircle",	"Solid",	"C://Users//deane//GitHub//Coleccion//Semicircles//Colección_Red_Semicircle_3.png");
		Card	rSE1	=	new	Card("Red",	1,	"Semicircle",	"Empty",	"C://Users//deane//GitHub//Coleccion//Semicircles//Colección_Red_Semicircle_E_1.png"); 
		Card	rSE2	=	new	Card("Red",	2,	"Semicircle",	"Empty",	"C://Users//deane//GitHub//Coleccion//Semicircles//Colección_Red_Semicircle_E_2.png");
		Card	rSE3	=	new	Card("Red",	3,	"Semicircle",	"Empty",	"C://Users//deane//GitHub//Coleccion//Semicircles//Colección_Red_Semicircle_E_3.png");
		Card	rSS1	=	new	Card("Red",	1,	"Semicircle",	"Grid",	"C://Users//deane//GitHub//Coleccion//Semicircles//Colección_Red_Semicircle_S_1.png"); 
		Card	rSS2	=	new	Card("Red",	2,	"Semicircle",	"Grid",	"C://Users//deane//GitHub//Coleccion//Semicircles//Colección_Red_Semicircle_S_2.png");
		Card	rSS3	=	new	Card("Red",	3,	"Semicircle",	"Grid",	"C://Users//deane//GitHub//Coleccion//Semicircles//Colección_Red_Semicircle_S_3.png");
		Card	bT1	=	new	Card("Blue",	1,	"Triangle",	"Solid",	"C://Users//deane//GitHub//Coleccion//Triangles//Colección_Blue_Triangle_1.png"); 
		Card	bT2	=	new	Card("Blue",	2,	"Triangle",	"Solid",	"C://Users//deane//GitHub//Coleccion//Triangles//Colección_Blue_Triangle_2.png");
		Card	bT3	=	new	Card("Blue",	3,	"Triangle",	"Solid",	"C://Users//deane//GitHub//Coleccion//Triangles//Colección_Blue_Triangle_3.png");
		Card	bTE1	=	new	Card("Blue",	1,	"Triangle",	"Empty",	"C://Users//deane//GitHub//Coleccion//Triangles//Colección_Blue_Triangle_E_1.png"); 
		Card	bTE2	=	new	Card("Blue",	2,	"Triangle",	"Empty",	"C://Users//deane//GitHub//Coleccion//Triangles//Colección_Blue_Triangle_E_2.png");
		Card	bTE3	=	new	Card("Blue",	3,	"Triangle",	"Empty",	"C://Users//deane//GitHub//Coleccion//Triangles//Colección_Blue_Triangle_E_3.png");
		Card	bTS1	=	new	Card("Blue",	1,	"Triangle",	"Grid",	"C://Users//deane//GitHub//Coleccion//Triangles//Colección_Blue_Triangle_S_1.png"); 
		Card	bTS2	=	new	Card("Blue",	2,	"Triangle",	"Grid",	"C://Users//deane//GitHub//Coleccion//Triangles//Colección_Blue_Triangle_S_2.png");
		Card	bTS3	=	new	Card("Blue",	3,	"Triangle",	"Grid",	"C://Users//deane//GitHub//Coleccion//Triangles//Colección_Blue_Triangle_S_3.png");
		Card	gT1	=	new	Card("Green",	1,	"Triangle",	"Solid",	"C://Users//deane//GitHub//Coleccion//Triangles//Colección_Green_Triangle_1.png"); 
		Card	gT2	=	new	Card("Green",	2,	"Triangle",	"Solid",	"C://Users//deane//GitHub//Coleccion//Triangles//Colección_Green_Triangle_2.png");
		Card	gT3	=	new	Card("Green",	3,	"Triangle",	"Solid",	"C://Users//deane//GitHub//Coleccion//Triangles//Colección_Green_Triangle_3.png");
		Card	gTE1	=	new	Card("Green",	1,	"Triangle",	"Empty",	"C://Users//deane//GitHub//Coleccion//Triangles//Colección_Green_Triangle_E_1.png"); 
		Card	gTE2	=	new	Card("Green",	2,	"Triangle",	"Empty",	"C://Users//deane//GitHub//Coleccion//Triangles//Colección_Green_Triangle_E_2.png");
		Card	gTE3	=	new	Card("Green",	3,	"Triangle",	"Empty",	"C://Users//deane//GitHub//Coleccion//Triangles//Colección_Green_Triangle_E_3.png");
		Card	gTS1	=	new	Card("Green",	1,	"Triangle",	"Grid",	"C://Users//deane//GitHub//Coleccion//Triangles//Colección_Green_Triangle_S_1.png"); 
		Card	gTS2	=	new	Card("Green",	2,	"Triangle",	"Grid",	"C://Users//deane//GitHub//Coleccion//Triangles//Colección_Green_Triangle_S_2.png");
		Card	gTS3	=	new	Card("Green",	3,	"Triangle",	"Grid",	"C://Users//deane//GitHub//Coleccion//Triangles//Colección_Green_Triangle_S_3.png");
		Card	oT1	=	new	Card("Orange",	1,	"Triangle",	"Solid",	"C://Users//deane//GitHub//Coleccion//Triangles//Colección_Orange_Triangle_1.png"); 
		Card	oT2	=	new	Card("Orange",	2,	"Triangle",	"Solid",	"C://Users//deane//GitHub//Coleccion//Triangles//Colección_Orange_Triangle_2.png");
		Card	oT3	=	new	Card("Orange",	3,	"Triangle",	"Solid",	"C://Users//deane//GitHub//Coleccion//Triangles//Colección_Orange_Triangle_3.png");
		Card	oTE1	=	new	Card("Orange",	1,	"Triangle",	"Empty",	"C://Users//deane//GitHub//Coleccion//Triangles//Colección_Orange_Triangle_E_1.png"); 
		Card	oTE2	=	new	Card("Orange",	2,	"Triangle",	"Empty",	"C://Users//deane//GitHub//Coleccion//Triangles//Colección_Orange_Triangle_E_2.png");
		Card	oTE3	=	new	Card("Orange",	3,	"Triangle",	"Empty",	"C://Users//deane//GitHub//Coleccion//Triangles//Colección_Orange_Triangle_E_3.png");
		Card	oTS1	=	new	Card("Orange",	1,	"Triangle",	"Grid",	"C://Users//deane//GitHub//Coleccion//Triangles//Colección_Orange_Triangle_S_1.png"); 
		Card	oTS2	=	new	Card("Orange",	2,	"Triangle",	"Grid",	"C://Users//deane//GitHub//Coleccion//Triangles//Colección_Orange_Triangle_S_2.png");
		Card	oTS3	=	new	Card("Orange",	3,	"Triangle",	"Grid",	"C://Users//deane//GitHub//Coleccion//Triangles//Colección_Orange_Triangle_S_3.png");
		Card	rT1	=	new	Card("Red",	1,	"Triangle",	"Solid",	"C://Users//deane//GitHub//Coleccion//Triangles//Colección_Red_Triangle_1.png"); 
		Card	rT2	=	new	Card("Red",	2,	"Triangle",	"Solid",	"C://Users//deane//GitHub//Coleccion//Triangles//Colección_Red_Triangle_2.png");
		Card	rT3	=	new	Card("Red",	3,	"Triangle",	"Solid",	"C://Users//deane//GitHub//Coleccion//Triangles//Colección_Red_Triangle_3.png");
		Card	rTE1	=	new	Card("Red",	1,	"Triangle",	"Empty",	"C://Users//deane//GitHub//Coleccion//Triangles//Colección_Red_Triangle_E_1.png"); 
		Card	rTE2	=	new	Card("Red",	2,	"Triangle",	"Empty",	"C://Users//deane//GitHub//Coleccion//Triangles//Colección_Red_Triangle_E_2.png");
		Card	rTE3	=	new	Card("Red",	3,	"Triangle",	"Empty",	"C://Users//deane//GitHub//Coleccion//Triangles//Colección_Red_Triangle_E_3.png");
		Card	rTS1	=	new	Card("Red",	1,	"Triangle",	"Grid",	"C://Users//deane//GitHub//Coleccion//Triangles//Colección_Red_Triangle_S_1.png"); 
		Card	rTS2	=	new	Card("Red",	2,	"Triangle",	"Grid",	"C://Users//deane//GitHub//Coleccion//Triangles//Colección_Red_Triangle_S_2.png");
		Card	rTS3	=	new	Card("Red",	3,	"Triangle",	"Grid",	"C://Users//deane//GitHub//Coleccion//Triangles//Colección_Red_Triangle_S_3.png");
		
		Image blueP1i = new Image(new FileInputStream(bP1.path));
    	Image blueP2i = new Image(new FileInputStream(bP2.path));
    	Image blueP3i = new Image(new FileInputStream(bP3.path));
    	Image blueP1ei = new Image(new FileInputStream(bPE1.path));
    	Image blueP2ei = new Image(new FileInputStream(bPE2.path));
    	Image blueP3ei = new Image(new FileInputStream(bPE3.path));
    	Image blueP1gi = new Image(new FileInputStream(bPS1.path));
    	Image blueP2gi = new Image(new FileInputStream(bPS2.path));
    	Image blueP3gi = new Image(new FileInputStream(bPS3.path));
    	Image greenP1i = new Image(new FileInputStream(gP1.path));
    	Image greenP2i = new Image(new FileInputStream(gP2.path));
    	Image greenP3i = new Image(new FileInputStream(gP3.path));
    	Image greenP1ei = new Image(new FileInputStream(gPE1.path));
    	Image greenP2ei = new Image(new FileInputStream(gPE2.path));
    	Image greenP3ei = new Image(new FileInputStream(gPE3.path));
    	Image greenP1gi = new Image(new FileInputStream(gPS1.path));
    	Image greenP2gi = new Image(new FileInputStream(gPS2.path));
    	Image greenP3gi = new Image(new FileInputStream(gPS3.path));
    	Image orangeP1i = new Image(new FileInputStream(oP1.path));
    	Image orangeP2i = new Image(new FileInputStream(oP2.path));
    	Image orangeP3i = new Image(new FileInputStream(oP3.path));
    	Image orangeP1ei = new Image(new FileInputStream(oPE1.path));
    	Image orangeP2ei = new Image(new FileInputStream(oPE2.path));
    	Image orangeP3ei = new Image(new FileInputStream(oPE3.path));
    	Image orangeP1gi = new Image(new FileInputStream(oPS1.path));
    	Image orangeP2gi = new Image(new FileInputStream(oPS2.path));
    	Image orangeP3gi = new Image(new FileInputStream(oPS3.path));
    	Image redP1i = new Image(new FileInputStream(rP1.path));
    	Image redP2i = new Image(new FileInputStream(rP2.path));
    	Image redP3i = new Image(new FileInputStream(rP3.path));
    	Image redP1ei = new Image(new FileInputStream(rPE1.path));
    	Image redP2ei = new Image(new FileInputStream(rPE2.path));
    	Image redP3ei = new Image(new FileInputStream(rPE3.path));
    	Image redP1gi = new Image(new FileInputStream(rPS1.path));
    	Image redP2gi = new Image(new FileInputStream(rPS2.path));
    	Image redP3gi = new Image(new FileInputStream(rPS3.path));
    	Image blueR1i = new Image(new FileInputStream(bR1.path));
    	Image blueR2i = new Image(new FileInputStream(bR2.path));
    	Image blueR3i = new Image(new FileInputStream(bR3.path));
    	Image blueR1ei = new Image(new FileInputStream(bRE1.path));
    	Image blueR2ei = new Image(new FileInputStream(bRE2.path));
    	Image blueR3ei = new Image(new FileInputStream(bRE3.path));
    	Image blueR1gi = new Image(new FileInputStream(bRS1.path));
    	Image blueR2gi = new Image(new FileInputStream(bRS2.path));
    	Image blueR3gi = new Image(new FileInputStream(bRS3.path));
    	Image greenR1i = new Image(new FileInputStream(gR1.path));
    	Image greenR2i = new Image(new FileInputStream(gR2.path));
    	Image greenR3i = new Image(new FileInputStream(gR3.path));
    	Image greenR1ei = new Image(new FileInputStream(gRE1.path));
    	Image greenR2ei = new Image(new FileInputStream(gRE2.path));
    	Image greenR3ei = new Image(new FileInputStream(gRE3.path));
    	Image greenR1gi = new Image(new FileInputStream(gRS1.path));
    	Image greenR2gi = new Image(new FileInputStream(gRS2.path));
    	Image greenR3gi = new Image(new FileInputStream(gRS3.path));
    	Image orangeR1i = new Image(new FileInputStream(oR1.path));
    	Image orangeR2i = new Image(new FileInputStream(oR2.path));
    	Image orangeR3i = new Image(new FileInputStream(oR3.path));
    	Image orangeR1ei = new Image(new FileInputStream(oRE1.path));
    	Image orangeR2ei = new Image(new FileInputStream(oRE2.path));
    	Image orangeR3ei = new Image(new FileInputStream(oRE3.path));
    	Image orangeR1gi = new Image(new FileInputStream(oRS1.path));
    	Image orangeR2gi = new Image(new FileInputStream(oRS2.path));
    	Image orangeR3gi = new Image(new FileInputStream(oRS3.path));
    	Image redR1i = new Image(new FileInputStream(rR1.path));
    	Image redR2i = new Image(new FileInputStream(rR2.path));
    	Image redR3i = new Image(new FileInputStream(rR3.path));
    	Image redR1ei = new Image(new FileInputStream(rRE1.path));
    	Image redR2ei = new Image(new FileInputStream(rRE2.path));
    	Image redR3ei = new Image(new FileInputStream(rRE3.path));
    	Image redR1gi = new Image(new FileInputStream(rRS1.path));
    	Image redR2gi = new Image(new FileInputStream(rRS2.path));
    	Image redR3gi = new Image(new FileInputStream(rRS3.path));
    	Image blueS1i = new Image(new FileInputStream(bS1.path));
    	Image blueS2i = new Image(new FileInputStream(bS2.path));
    	Image blueS3i = new Image(new FileInputStream(bS3.path));
    	Image blueS1ei = new Image(new FileInputStream(bSE1.path));
    	Image blueS2ei = new Image(new FileInputStream(bSE2.path));
    	Image blueS3ei = new Image(new FileInputStream(bSE3.path));
    	Image blueS1gi = new Image(new FileInputStream(bSS1.path));
    	Image blueS2gi = new Image(new FileInputStream(bSS2.path));
    	Image blueS3gi = new Image(new FileInputStream(bSS3.path));
    	Image greenS1i = new Image(new FileInputStream(gS1.path));
    	Image greenS2i = new Image(new FileInputStream(gS2.path));
    	Image greenS3i = new Image(new FileInputStream(gS3.path));
    	Image greenS1ei = new Image(new FileInputStream(gSE1.path));
    	Image greenS2ei = new Image(new FileInputStream(gSE2.path));
    	Image greenS3ei = new Image(new FileInputStream(gSE3.path));
    	Image greenS1gi = new Image(new FileInputStream(gSS1.path));
    	Image greenS2gi = new Image(new FileInputStream(gSS2.path));
    	Image greenS3gi = new Image(new FileInputStream(gSS3.path));
    	Image orangeS1i = new Image(new FileInputStream(oS1.path));
    	Image orangeS2i = new Image(new FileInputStream(oS2.path));
    	Image orangeS3i = new Image(new FileInputStream(oS3.path));
    	Image orangeS1ei = new Image(new FileInputStream(oSE1.path));
    	Image orangeS2ei = new Image(new FileInputStream(oSE2.path));
    	Image orangeS3ei = new Image(new FileInputStream(oSE3.path));
    	Image orangeS1gi = new Image(new FileInputStream(oSS1.path));
    	Image orangeS2gi = new Image(new FileInputStream(oSS2.path));
    	Image orangeS3gi = new Image(new FileInputStream(oSS3.path));
    	Image redS1i = new Image(new FileInputStream(rS1.path));
    	Image redS2i = new Image(new FileInputStream(rS2.path));
    	Image redS3i = new Image(new FileInputStream(rS3.path));
    	Image redS1ei = new Image(new FileInputStream(rSE1.path));
    	Image redS2ei = new Image(new FileInputStream(rSE2.path));
    	Image redS3ei = new Image(new FileInputStream(rSE3.path));
    	Image redS1gi = new Image(new FileInputStream(rSS1.path));
    	Image redS2gi = new Image(new FileInputStream(rSS2.path));
    	Image redS3gi = new Image(new FileInputStream(rSS3.path));
    	Image blueT1i = new Image(new FileInputStream(bT1.path));
    	Image blueT2i = new Image(new FileInputStream(bT2.path));
    	Image blueT3i = new Image(new FileInputStream(bT3.path));
    	Image blueT1ei = new Image(new FileInputStream(bTE1.path));
    	Image blueT2ei = new Image(new FileInputStream(bTE2.path));
    	Image blueT3ei = new Image(new FileInputStream(bTE3.path));
    	Image blueT1gi = new Image(new FileInputStream(bTS1.path));
    	Image blueT2gi = new Image(new FileInputStream(bTS2.path));
    	Image blueT3gi = new Image(new FileInputStream(bTS3.path));
    	Image greenT1i = new Image(new FileInputStream(gT1.path));
    	Image greenT2i = new Image(new FileInputStream(gT2.path));
    	Image greenT3i = new Image(new FileInputStream(gT3.path));
    	Image greenT1ei = new Image(new FileInputStream(gTE1.path));
    	Image greenT2ei = new Image(new FileInputStream(gTE2.path));
    	Image greenT3ei = new Image(new FileInputStream(gTE3.path));
    	Image greenT1gi = new Image(new FileInputStream(gTS1.path));
    	Image greenT2gi = new Image(new FileInputStream(gTS2.path));
    	Image greenT3gi = new Image(new FileInputStream(gTS3.path));
    	Image orangeT1i = new Image(new FileInputStream(oT1.path));
    	Image orangeT2i = new Image(new FileInputStream(oT2.path));
    	Image orangeT3i = new Image(new FileInputStream(oT3.path));
    	Image orangeT1ei = new Image(new FileInputStream(oTE1.path));
    	Image orangeT2ei = new Image(new FileInputStream(oTE2.path));
    	Image orangeT3ei = new Image(new FileInputStream(oTE3.path));
    	Image orangeT1gi = new Image(new FileInputStream(oTS1.path));
    	Image orangeT2gi = new Image(new FileInputStream(oTS2.path));
    	Image orangeT3gi = new Image(new FileInputStream(oTS3.path));
    	Image redT1i = new Image(new FileInputStream(rT1.path));
    	Image redT2i = new Image(new FileInputStream(rT2.path));
    	Image redT3i = new Image(new FileInputStream(rT3.path));
    	Image redT1ei = new Image(new FileInputStream(rTE1.path));
    	Image redT2ei = new Image(new FileInputStream(rTE2.path));
    	Image redT3ei = new Image(new FileInputStream(rTE3.path));
    	Image redT1gi = new Image(new FileInputStream(rTS1.path));
    	Image redT2gi = new Image(new FileInputStream(rTS2.path));
    	Image redT3gi = new Image(new FileInputStream(rTS3.path));    	
    	
    	bP1.imgAdd(	blueP1i	);
    	bP2.imgAdd(	blueP2i	);
    	bP3.imgAdd(	blueP3i	);
    	bPE1.imgAdd(	blueP1ei	);
    	bPE2.imgAdd(	blueP2ei	);
    	bPE3.imgAdd(	blueP3ei	);
    	bPS1.imgAdd(	blueP1gi	);
    	bPS2.imgAdd(	blueP2gi	);
    	bPS3.imgAdd(	blueP3gi	);
    	gP1.imgAdd(	greenP1i	);
    	gP2.imgAdd(	greenP2i	);
    	gP3.imgAdd(	greenP3i	);
    	gPE1.imgAdd(	greenP1ei	);
    	gPE2.imgAdd(	greenP2ei	);
    	gPE3.imgAdd(	greenP3ei	);
    	gPS1.imgAdd(	greenP1gi	);
    	gPS2.imgAdd(	greenP2gi	);
    	gPS3.imgAdd(	greenP3gi	);
    	oP1.imgAdd(	orangeP1i	);
    	oP2.imgAdd(	orangeP2i	);
    	oP3.imgAdd(	orangeP3i	);
    	oPE1.imgAdd(	orangeP1ei	);
    	oPE2.imgAdd(	orangeP2ei	);
    	oPE3.imgAdd(	orangeP3ei	);
    	oPS1.imgAdd(	orangeP1gi	);
    	oPS2.imgAdd(	orangeP2gi	);
    	oPS3.imgAdd(	orangeP3gi	);
    	rP1.imgAdd(	redP1i	);
    	rP2.imgAdd(	redP2i	);
    	rP3.imgAdd(	redP3i	);
    	rPE1.imgAdd(	redP1ei	);
    	rPE2.imgAdd(	redP2ei	);
    	rPE3.imgAdd(	redP3ei	);
    	rPS1.imgAdd(	redP1gi	);
    	rPS2.imgAdd(	redP2gi	);
    	rPS3.imgAdd(	redP3gi	);
    	bR1.imgAdd(	blueR1i	);
    	bR2.imgAdd(	blueR2i	);
    	bR3.imgAdd(	blueR3i	);
    	bRE1.imgAdd(	blueR1ei	);
    	bRE2.imgAdd(	blueR2ei	);
    	bRE3.imgAdd(	blueR3ei	);
    	bRS1.imgAdd(	blueR1gi	);
    	bRS2.imgAdd(	blueR2gi	);
    	bRS3.imgAdd(	blueR3gi	);
    	gR1.imgAdd(	greenR1i	);
    	gR2.imgAdd(	greenR2i	);
    	gR3.imgAdd(	greenR3i	);
    	gRE1.imgAdd(	greenR1ei	);
    	gRE2.imgAdd(	greenR2ei	);
    	gRE3.imgAdd(	greenR3ei	);
    	gRS1.imgAdd(	greenR1gi	);
    	gRS2.imgAdd(	greenR2gi	);
    	gRS3.imgAdd(	greenR3gi	);
    	oR1.imgAdd(	orangeR1i	);
    	oR2.imgAdd(	orangeR2i	);
    	oR3.imgAdd(	orangeR3i	);
    	oRE1.imgAdd(	orangeR1ei	);
    	oRE2.imgAdd(	orangeR2ei	);
    	oRE3.imgAdd(	orangeR3ei	);
    	oRS1.imgAdd(	orangeR1gi	);
    	oRS2.imgAdd(	orangeR2gi	);
    	oRS3.imgAdd(	orangeR3gi	);
    	rR1.imgAdd(	redR1i	);
    	rR2.imgAdd(	redR2i	);
    	rR3.imgAdd(	redR3i	);
    	rRE1.imgAdd(	redR1ei	);
    	rRE2.imgAdd(	redR2ei	);
    	rRE3.imgAdd(	redR3ei	);
    	rRS1.imgAdd(	redR1gi	);
    	rRS2.imgAdd(	redR2gi	);
    	rRS3.imgAdd(	redR3gi	);
    	bS1.imgAdd(	blueS1i	);
    	bS2.imgAdd(	blueS2i	);
    	bS3.imgAdd(	blueS3i	);
    	bSE1.imgAdd(	blueS1ei	);
    	bSE2.imgAdd(	blueS2ei	);
    	bSE3.imgAdd(	blueS3ei	);
    	bSS1.imgAdd(	blueS1gi	);
    	bSS2.imgAdd(	blueS2gi	);
    	bSS3.imgAdd(	blueS3gi	);
    	gS1.imgAdd(	greenS1i	);
    	gS2.imgAdd(	greenS2i	);
    	gS3.imgAdd(	greenS3i	);
    	gSE1.imgAdd(	greenS1ei	);
    	gSE2.imgAdd(	greenS2ei	);
    	gSE3.imgAdd(	greenS3ei	);
    	gSS1.imgAdd(	greenS1gi	);
    	gSS2.imgAdd(	greenS2gi	);
    	gSS3.imgAdd(	greenS3gi	);
    	oS1.imgAdd(	orangeS1i	);
    	oS2.imgAdd(	orangeS2i	);
    	oS3.imgAdd(	orangeS3i	);
    	oSE1.imgAdd(	orangeS1ei	);
    	oSE2.imgAdd(	orangeS2ei	);
    	oSE3.imgAdd(	orangeS3ei	);
    	oSS1.imgAdd(	orangeS1gi	);
    	oSS2.imgAdd(	orangeS2gi	);
    	oSS3.imgAdd(	orangeS3gi	);
    	rS1.imgAdd(	redS1i	);
    	rS2.imgAdd(	redS2i	);
    	rS3.imgAdd(	redS3i	);
    	rSE1.imgAdd(	redS1ei	);
    	rSE2.imgAdd(	redS2ei	);
    	rSE3.imgAdd(	redS3ei	);
    	rSS1.imgAdd(	redS1gi	);
    	rSS2.imgAdd(	redS2gi	);
    	rSS3.imgAdd(	redS3gi	);
    	bT1.imgAdd(	blueT1i	);
    	bT2.imgAdd(	blueT2i	);
    	bT3.imgAdd(	blueT3i	);
    	bTE1.imgAdd(	blueT1ei	);
    	bTE2.imgAdd(	blueT2ei	);
    	bTE3.imgAdd(	blueT3ei	);
    	bTS1.imgAdd(	blueT1gi	);
    	bTS2.imgAdd(	blueT2gi	);
    	bTS3.imgAdd(	blueT3gi	);
    	gT1.imgAdd(	greenT1i	);
    	gT2.imgAdd(	greenT2i	);
    	gT3.imgAdd(	greenT3i	);
    	gTE1.imgAdd(	greenT1ei	);
    	gTE2.imgAdd(	greenT2ei	);
    	gTE3.imgAdd(	greenT3ei	);
    	gTS1.imgAdd(	greenT1gi	);
    	gTS2.imgAdd(	greenT2gi	);
    	gTS3.imgAdd(	greenT3gi	);
    	oT1.imgAdd(	orangeT1i	);
    	oT2.imgAdd(	orangeT2i	);
    	oT3.imgAdd(	orangeT3i	);
    	oTE1.imgAdd(	orangeT1ei	);
    	oTE2.imgAdd(	orangeT2ei	);
    	oTE3.imgAdd(	orangeT3ei	);
    	oTS1.imgAdd(	orangeT1gi	);
    	oTS2.imgAdd(	orangeT2gi	);
    	oTS3.imgAdd(	orangeT3gi	);
    	rT1.imgAdd(	redT1i	);
    	rT2.imgAdd(	redT2i	);
    	rT3.imgAdd(	redT3i	);
    	rTE1.imgAdd(	redT1ei	);
    	rTE2.imgAdd(	redT2ei	);
    	rTE3.imgAdd(	redT3ei	);
    	rTS1.imgAdd(	redT1gi	);
    	rTS2.imgAdd(	redT2gi	);
    	rTS3.imgAdd(	redT3gi	);
    	
    	this.push(	bP1	);
    	this.push(	bP2	);
    	this.push(	bP3	);
    	this.push(	bPE1	);
    	this.push(	bPE2	);
    	this.push(	bPE3	);
    	this.push(	bPS1	);
    	this.push(	bPS2	);
    	this.push(	bPS3	);
    	this.push(	gP1	);
    	this.push(	gP2	);
    	this.push(	gP3	);
    	this.push(	gPE1	);
    	this.push(	gPE2	);
    	this.push(	gPE3	);
    	this.push(	gPS1	);
    	this.push(	gPS2	);
    	this.push(	gPS3	);
    	this.push(	oP1	);
    	this.push(	oP2	);
    	this.push(	oP3	);
    	this.push(	oPE1	);
    	this.push(	oPE2	);
    	this.push(	oPE3	);
    	this.push(	oPS1	);
    	this.push(	oPS2	);
    	this.push(	oPS3	);
    	this.push(	rP1	);
    	this.push(	rP2	);
    	this.push(	rP3	);
    	this.push(	rPE1	);
    	this.push(	rPE2	);
    	this.push(	rPE3	);
    	this.push(	rPS1	);
    	this.push(	rPS2	);
    	this.push(	rPS3	);
    	this.push(	bR1	);
    	this.push(	bR2	);
    	this.push(	bR3	);
    	this.push(	bRE1	);
    	this.push(	bRE2	);
    	this.push(	bRE3	);
    	this.push(	bRS1	);
    	this.push(	bRS2	);
    	this.push(	bRS3	);
    	this.push(	gR1	);
    	this.push(	gR2	);
    	this.push(	gR3	);
    	this.push(	gRE1	);
    	this.push(	gRE2	);
    	this.push(	gRE3	);
    	this.push(	gRS1	);
    	this.push(	gRS2	);
    	this.push(	gRS3	);
    	this.push(	oR1	);
    	this.push(	oR2	);
    	this.push(	oR3	);
    	this.push(	oRE1	);
    	this.push(	oRE2	);
    	this.push(	oRE3	);
    	this.push(	oRS1	);
    	this.push(	oRS2	);
    	this.push(	oRS3	);
    	this.push(	rR1	);
    	this.push(	rR2	);
    	this.push(	rR3	);
    	this.push(	rRE1	);
    	this.push(	rRE2	);
    	this.push(	rRE3	);
    	this.push(	rRS1	);
    	this.push(	rRS2	);
    	this.push(	rRS3	);
    	this.push(	bS1	);
    	this.push(	bS2	);
    	this.push(	bS3	);
    	this.push(	bSE1	);
    	this.push(	bSE2	);
    	this.push(	bSE3	);
    	this.push(	bSS1	);
    	this.push(	bSS2	);
    	this.push(	bSS3	);
    	this.push(	gS1	);
    	this.push(	gS2	);
    	this.push(	gS3	);
    	this.push(	gSE1	);
    	this.push(	gSE2	);
    	this.push(	gSE3	);
    	this.push(	gSS1	);
    	this.push(	gSS2	);
    	this.push(	gSS3	);
    	this.push(	oS1	);
    	this.push(	oS2	);
    	this.push(	oS3	);
    	this.push(	oSE1	);
    	this.push(	oSE2	);
    	this.push(	oSE3	);
    	this.push(	oSS1	);
    	this.push(	oSS2	);
    	this.push(	oSS3	);
    	this.push(	rS1	);
    	this.push(	rS2	);
    	this.push(	rS3	);
    	this.push(	rSE1	);
    	this.push(	rSE2	);
    	this.push(	rSE3	);
    	this.push(	rSS1	);
    	this.push(	rSS2	);
    	this.push(	rSS3	);
    	this.push(	bT1	);
    	this.push(	bT2	);
    	this.push(	bT3	);
    	this.push(	bTE1	);
    	this.push(	bTE2	);
    	this.push(	bTE3	);
    	this.push(	bTS1	);
    	this.push(	bTS2	);
    	this.push(	bTS3	);
    	this.push(	gT1	);
    	this.push(	gT2	);
    	this.push(	gT3	);
    	this.push(	gTE1	);
    	this.push(	gTE2	);
    	this.push(	gTE3	);
    	this.push(	gTS1	);
    	this.push(	gTS2	);
    	this.push(	gTS3	);
    	this.push(	oT1	);
    	this.push(	oT2	);
    	this.push(	oT3	);
    	this.push(	oTE1	);
    	this.push(	oTE2	);
    	this.push(	oTE3	);
    	this.push(	oTS1	);
    	this.push(	oTS2	);
    	this.push(	oTS3	);
    	this.push(	rT1	);
    	this.push(	rT2	);
    	this.push(	rT3	);
    	this.push(	rTE1	);
    	this.push(	rTE2	);
    	this.push(	rTE3	);
    	this.push(	rTS1	);
    	this.push(	rTS2	);
    	this.push(	rTS3	);
	}
}
